export { default as Header } from './Header'
export { default as Feedback } from './Feedback'
export { default as About } from './About'
export { default as Products } from './Products'
export { default as Contact } from './Contact'
export { default as Blog } from './Blog'
export { default as Footer } from './Footer'
export {default as Main} from './Main'